apiVersion: v1
kind: Service
metadata:
  name: eks-apollo
  namespace: eks-apollo
  labels:
    app: eks-apollo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 7580
      protocol: TCP
      name: http
  selector:
    app: eks-apollo
