---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-apollo
  namespace: eks-apollo
  labels:
    app: eks-apollo
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-apollo
  template:
    metadata:
      labels:
        app: eks-apollo
    spec:
      containers:
      - name: eks-apollo
        image: 758178152797.dkr.ecr.us-west-2.amazonaws.com/eks-apollo:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7580
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
